pipeline:
  identifier: Build_shankaranandh_gosample_1701899036460
  name: Build gosample
  orgIdentifier: cvng
  projectIdentifier: srmsockshop
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: shankargh
        repoName: shankaranandh/gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    command: go test -v ./...
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
